"""Add percentage field to segment

Revision ID: 0ed66b2be99d
Revises: edc5c37b9bf5
Create Date: 2026-02-21 19:57:05.155238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed66b2be99d'
down_revision: Union[str, None] = 'edc5c37b9bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('segment', sa.Column('percentage', sa.Float(), nullable=True))

    # Set default value for existing rows (distribute equally among segments per experiment)
    from sqlalchemy import text
    connection = op.get_bind()

    # Get all experiments and their segment counts
    result = connection.execute(text(
        "SELECT experiment_id, COUNT(*) as segment_count FROM segment GROUP BY experiment_id"
    ))

    for row in result:
        experiment_id = row[0]
        segment_count = row[1]
        equal_percentage = 1.0 / segment_count

        # Update all segments for this experiment
        connection.execute(text(
            f"UPDATE segment SET percentage = {equal_percentage} WHERE experiment_id = {experiment_id}"
        ))

    # Now make the column non-nullable
    op.alter_column('segment', 'percentage', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segment', 'percentage')
    # ### end Alembic commands ###
