"""Add GitHub project fields

Revision ID: 8c0bb8b1f47e
Revises: 
Create Date: 2026-02-21 18:57:39.944239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c0bb8b1f47e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_percentage', sa.Float(), nullable=False),
    sa.Column('number_of_segments', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_id'), 'experiment', ['id'], unique=False)
    op.create_index(op.f('ix_experiment_project_id'), 'experiment', ['project_id'], unique=False)
    op.create_table('insight_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('json_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plot_image', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_experiment_id'), 'segment', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_segment_id'), 'segment', ['id'], unique=False)
    op.create_table('event_tracked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('event_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_tracked_experiment_id'), 'event_tracked', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_event_tracked_id'), 'event_tracked', ['id'], unique=False)
    op.create_index(op.f('ix_event_tracked_project_id'), 'event_tracked', ['project_id'], unique=False)
    op.create_index(op.f('ix_event_tracked_segment_id'), 'event_tracked', ['segment_id'], unique=False)
    op.add_column('project', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('project', sa.Column('stars_count', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('forks_count', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('default_branch', sa.String(), nullable=True))
    op.add_column('project', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'language')
    op.drop_column('project', 'default_branch')
    op.drop_column('project', 'forks_count')
    op.drop_column('project', 'stars_count')
    op.drop_column('project', 'full_name')
    op.drop_index(op.f('ix_event_tracked_segment_id'), table_name='event_tracked')
    op.drop_index(op.f('ix_event_tracked_project_id'), table_name='event_tracked')
    op.drop_index(op.f('ix_event_tracked_id'), table_name='event_tracked')
    op.drop_index(op.f('ix_event_tracked_experiment_id'), table_name='event_tracked')
    op.drop_table('event_tracked')
    op.drop_index(op.f('ix_segment_id'), table_name='segment')
    op.drop_index(op.f('ix_segment_experiment_id'), table_name='segment')
    op.drop_table('segment')
    op.drop_table('insight_data')
    op.drop_index(op.f('ix_experiment_project_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_id'), table_name='experiment')
    op.drop_table('experiment')
    # ### end Alembic commands ###
